exp_name: transformer_nerf
inference: False
resume: False
ckpt: ""

data:
  robot_name: "panda"
  root: "data/franka_arm_only2/"

  batch_size: 128
  num_workers: 16

  overfit_to_index: null
  trgt_img_size: [128, 128]
  ray_bundle_size: 256
  ray_patch_size: null


optim:
  lr: 4e-4
  total_steps: 1000000
  vis_every: 1000
  save_every: 1000


model:
  rf:
    feat_dim: 128
    num_layers: 4
    skip_layer_idx: 2


  renderer:
    n_coarse: 128
    n_fine: 64
    perturb: 0.0
    use_lindisp: False
    chunk: 32768 # 32 * 1024 = 32768
    bkgd_color:


