exp_name: pixel_nerf
inference: False
resume: False
ckpt: ""

data:
  dataset_name: scene-rep
  rel_location: "data/franka_arm_only/"
  batch_size: 60
  num_workers: 16
  subsample_ray: 256
  norm_qpos_min: -1.0
  norm_qpos_max: 1.0
  near: 1.0
  far: 5.0
  debug: False
  img_res: [256, 256]


test_views:
  spherical:
    num_views: 100
    radius: 2.0
    cam_height: 1.5
    lookat: [0., 0., 0.5]

optim:
  lr: 1e-3
  total_steps: 1000000
  vis_every: 1000
  save_every: 1000


model:
  encoder:
    backbone: resnet18
  rf:
    n_feats: 512
    n_blocks: 3
    d_hidden: 128


  renderer:
    n_coarse: 64
    n_fine: 0
    perturb: 0.0
    use_lindisp: False
    chunk: 32768 # 32 * 1024 = 32768
    bkgd_color:


