exp_name: transformer_nerf
inference: False
resume: False
ckpt: ""

data:
  dataset_name: self-model
  rel_location: "data/ur5e/"
  batch_size: 160
  num_workers: 8
  subsample_ray: 256
  norm_qpos_min: -1.0
  norm_qpos_max: 1.0
  near: 0.0
  far: 2.7
  debug: False
  img_res: [256, 256]
  output_size: [128, 128]

  use_depth: False
  ret_patch: False


test_views:
  spherical:
    num_views: 100
    radius: 2.0
    cam_height: 1.5
    lookat: [0., 0., 0.5]

optim:
  lr: 1e-3
  total_steps: 1000000
  vis_every: 1000
  save_every: 1000


model:
  rf:
    feat_dim: 128
    pos_octave: 10
    ray_octave: 4
    n_joints: 6

    depth_render_head: 2
    token_mode: 'mult'


  renderer:
    n_coarse: 128
    n_fine: 0
    perturb: 0.0
    use_lindisp: False
    chunk: 32768 # 32 * 1024 = 32768
    bkgd_color:


