defaults:
  - push_env_cfg: pusher_only
dump_dir: "diff-force/diffusion-forcing/data/pusher_down_right"
num_trajs: 200
remove_exists: True
horizon: 50
debug: False
use_obj: True
train_val_split: 0.8
num_blocks: 1
object_type: ["rod"]
object_xy_pos: [[0, -0.25]]
use_flow: False