name: "ur5e"
dump_dir: "data/ur5e"
remove_exists: False
debug: False
cam_mode: custom

up_vector: [0., 0., 1.]
views:
  spherical:
    num_views: 8
    radius: 1.4
    cam_height: 1.4
    lookat: [0., 0., 0.5]
  base:
    cam_pos: [0., 0.1, 2.5]
    lookat: [0., 0., 0.]

robot:
  type: "ur5e"
  random_joint_pos: True

sensor:
  depth: False

num_samples: 100000
